[package]
name = "quilt"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.8.1"
ariadne = "0.1.5"
fxhash = "0.2.1"
colored = "2.0.0"
paste = "1.0.11"
arrayvec = "0.7.2"
packed_struct  = "0.10.1"
thiserror = "1.0.40"